<?PHP

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN UA_Products
 */
class UA_Products_sugar extends Basic
{
    var $new_schema = true;
    var $module_dir = 'UA_Products';
    var $object_name = 'UA_Products';
    var $table_name = 'ua_products';
    var $importable = true;
    var $disable_row_level_security = true; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
    var $id;
    var $name;
    var $date_entered;
    var $date_modified;
    var $modified_user_id;
    var $modified_by_name;
    var $created_by;
    var $created_by_name;
    var $description;
    var $deleted;
    var $created_by_link;
    var $modified_user_link;
    var $assigned_user_id;
    var $assigned_user_name;
    var $assigned_user_link;
    var $product_code;
    var $product_status;
    var $product_category;
    var $manufacturer;
    var $unit_price;
    var $commission_rate;
    var $tax;
    var $taxable;
    var $cost;
    var $currency_id;
    var $usage_unit;
    var $qty_in_stock;
    
    public function UA_Products_sugar()
    {
        parent::Basic();
    }

    public function bean_implements($interface)
    {
        switch ($interface)
        {
            case 'ACL':
                return true;
        }
        return false;
    }

}