<?php

$dictionary['UA_Products'] = array(
    'table' => 'ua_products',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'product_image' => array(
            'name' => 'product_image',
            'type' => 'ua_photo',
            'dbType' => 'varchar',
            'vname' => 'LBL_PRODUCT_IMAGE',
            'default' => 'noImage.gif',
            'len' => '255',
            'audited' => false,
            'massupdate' => 0,
        ),
        'product_code' =>
            array(
                'required' => false,
                'name' => 'product_code',
                'vname' => 'LBL_PRODUCT_CODE',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'product_status' =>
            array(
                'required' => false,
                'name' => 'product_status',
                'vname' => 'LBL_PRODUCT_STATUS',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'Active',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 100,
                'size' => '20',
                'options' => 'product_status_dom',
                'studio' => 'visible',
                'dependency' => false,
            ),
        'product_category' =>
            array(
                'required' => false,
                'name' => 'product_category',
                'vname' => 'LBL_PRODUCT_CATEGORY',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_product_categories',
                    'onListView' => true,
                    'include' => 'modules/UA_Products/products_utils.php',
                ),
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'manufacturer' =>
            array(
                'required' => false,
                'name' => 'manufacturer',
                'vname' => 'LBL_MANUFACTURER',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_manufactures',
                    'onListView' => true,
                    'include' => 'modules/UA_Products/products_utils.php',
                ),
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'unit_price' =>
            array(
                'required' => false,
                'name' => 'unit_price',
                'vname' => 'LBL_UNIT_PRICE',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
            ),
        'commission_rate' =>
            array(
                'required' => false,
                'name' => 'commission_rate',
                'vname' => 'LBL_COMMISSION_RATE',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '10',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),
        'tax' =>
            array(
                'required' => false,
                'name' => 'tax',
                'vname' => 'LBL_TAX',
                'type' => 'multienum',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'size' => '20',
                'options' => 'product_tax_dom',
                'studio' => 'visible',
                'isMultiSelect' => true,
            ),
        'taxable' =>
            array(
                'required' => false,
                'name' => 'taxable',
                'vname' => 'LBL_TAXABLE',
                'type' => 'bool',
                'massupdate' => 0,
                'default' => '1',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
            ),
        'cost' =>
            array(
                'required' => false,
                'name' => 'cost',
                'vname' => 'LBL_COST',
                'type' => 'currency',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 26,
                'size' => '20',
                'enable_range_search' => false,
                'precision' => 6,
            ),
        'currency_id' =>
            array(
                'required' => false,
                'name' => 'currency_id',
                'vname' => 'LBL_CURRENCY',
                'type' => 'currency_id',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => 0,
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 36,
                'size' => '20',
                'dbType' => 'id',
                'studio' => 'visible',
                'function' =>
                    array(
                        'name' => 'getCurrencyDropDown',
                        'returns' => 'html',
                    ),
            ),
        'usage_unit' =>
            array(
                'required' => false,
                'name' => 'usage_unit',
                'vname' => 'LBL_USAGE_UNIT',
                'type' => 'enum',
                'massupdate' => 0,
                'default' => 'Box',
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => 100,
                'size' => '20',
                'options' => 'product_usage_unit_dom',
                'studio' => 'visible',
                'dependency' => false,
            ),
        'qty_in_stock' =>
            array(
                'required' => false,
                'name' => 'qty_in_stock',
                'vname' => 'LBL_QTY_IN_STOCK',
                'type' => 'int',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => false,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '10',
                'size' => '20',
                'enable_range_search' => false,
                'disable_num_format' => '',
                'min' => false,
                'max' => false,
            ),

        'ua_contracts' => array(
            'name' => 'ua_contracts',
            'type' => 'link',
            'vname' => 'LBL_CONTRACTS',
            'relationship' => 'ua_contracts_products',
            'link_type' => 'one',
            'source' => 'non-db',
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager'))
{
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('UA_Products', 'UA_Products', array(
    'basic',
    'assignable'
));
